buildTree = {
	"Sightstone"                        -> {{"Ruby Crystal","Sightstone"}},
	"Trinity Force"                     -> {{"Zeal","Trinity Force"}, {"Brawler's Gloves","Zeal"}, {"Dagger","Zeal"}, {"Sheen","Trinity Force"}, {"Sapphire Crystal","Sheen"}, {"Amplifying Tome","Sheen"}, {"Phage","Trinity Force"}, {"Ruby Crystal","Phage"}, {"Long Sword","Phage"}},
	"Warden's Mail"                     -> {{"Cloth Armor","Warden's Mail"}, {"Cloth Armor","Warden's Mail"}},
	"Warmog's Armor"                    -> {{"Giant's Belt","Warmog's Armor"}, {"Ruby Crystal","Warmog's Armor"}, {"Rejuvenation Bead","Warmog's Armor"}, {"Rejuvenation Bead","Warmog's Armor"}},
	"Rabadon's Deathcap"                -> {{"Blasting Wand","Rabadon's Deathcap"}, {"Needlessly Large Rod","Rabadon's Deathcap"}},
	"Shard of True Ice"                 -> {{"Kage's Lucky Pick","Shard of True Ice"}, {"Amplifying Tome","Kage's Lucky Pick"}, {"Mana Manipulator","Shard of True Ice"}, {"Faerie Charm","Mana Manipulator"}},
	"Avarice Blade"                     -> {{"Brawler's Gloves","Avarice Blade"}},
	"Philosopher's Stone"               -> {{"Faerie Charm","Philosopher's Stone"}, {"Rejuvenation Bead","Philosopher's Stone"}},
	"Kage's Lucky Pick"                 -> {{"Amplifying Tome","Kage's Lucky Pick"}},
	"Vampiric Scepter"                  -> {{"Long Sword","Vampiric Scepter"}},
	"Fiendish Codex"                    -> {{"Amplifying Tome","Fiendish Codex"}},
	"Force of Nature"                   -> {{"Rejuvenation Bead","Force of Nature"}, {"Rejuvenation Bead","Force of Nature"}, {"Negatron Cloak","Force of Nature"}},
	"Orb of Winter"                     -> {{"Rejuvenation Bead","Orb of Winter"}, {"Rejuvenation Bead","Orb of Winter"}, {"Negatron Cloak","Orb of Winter"}},
	"Malady"                            -> {{"Dagger","Malady"}, {"Dagger","Malady"}, {"Amplifying Tome","Malady"}},
	"Nashor's Tooth"                    -> {{"Stinger","Nashor's Tooth"}, {"Dagger","Stinger"}, {"Dagger","Stinger"}, {"Fiendish Codex","Nashor's Tooth"}, {"Amplifying Tome","Fiendish Codex"}},
	"Rylai's Crystal Scepter"           -> {{"Blasting Wand","Rylai's Crystal Scepter"}, {"Amplifying Tome","Rylai's Crystal Scepter"}, {"Giant's Belt","Rylai's Crystal Scepter"}},
	"Boots of Mobility"                 -> {{"Boots of Speed","Boots of Mobility"}},
	"Wicked Hatchet"                    -> {{"Cloak of Agility","Wicked Hatchet"}, {"Long Sword","Wicked Hatchet"}},
	"Executioner's Calling"             -> {{"Avarice Blade","Executioner's Calling"}, {"Brawler's Gloves","Avarice Blade"}, {"Long Sword","Executioner's Calling"}},
	"Guinsoo's Rageblade"               -> {{"Blasting Wand","Guinsoo's Rageblade"}, {"Pickaxe","Guinsoo's Rageblade"}},
	"Madred's Bloodrazor"               -> {{"Madred's Razors","Madred's Bloodrazor"}, {"Cloth Armor","Madred's Razors"}, {"Hunter's Machete","Madred's Razors"}, {"Pickaxe","Madred's Bloodrazor"}, {"Recurve Bow","Madred's Bloodrazor"}},
	"Spirit Stone"                      -> {{"Hunter's Machete","Spirit Stone"}, {"Faerie Charm","Spirit Stone"}, {"Rejuvenation Bead","Spirit Stone"}},
	"Shurelya's Reverie"                -> {{"Kindlegem","Shurelya's Reverie"}, {"Ruby Crystal","Kindlegem"}, {"Philosopher's Stone","Shurelya's Reverie"}, {"Faerie Charm","Philosopher's Stone"}, {"Rejuvenation Bead","Philosopher's Stone"}},
	"Sword of the Divine"               -> {{"Recurve Bow","Sword of the Divine"}, {"Dagger","Sword of the Divine"}},
	"Heart of Gold"                     -> {{"Ruby Crystal","Heart of Gold"}},
	"The Brutalizer"                    -> {{"Long Sword","The Brutalizer"}, {"Long Sword","The Brutalizer"}},
	"Void Staff"                        -> {{"Blasting Wand","Void Staff"}, {"Amplifying Tome","Void Staff"}},
	"Haunting Guise"                    -> {{"Ruby Crystal","Haunting Guise"}, {"Amplifying Tome","Haunting Guise"}},
	"Leviathan"                         -> {{"Ruby Crystal","Leviathan"}},
	"Mercurial Scimitar"                -> {{"Quicksilver Sash","Mercurial Scimitar"}, {"Negatron Cloak","Quicksilver Sash"}, {"B. F. Sword","Mercurial Scimitar"}},
	"Quicksilver Sash"                  -> {{"Negatron Cloak","Quicksilver Sash"}},
	"Sword of the Occult"               -> {{"Long Sword","Sword of the Occult"}},
	"Youmuu's Ghostblade"               -> {{"Avarice Blade","Youmuu's Ghostblade"}, {"Brawler's Gloves","Avarice Blade"}, {"The Brutalizer","Youmuu's Ghostblade"}, {"Long Sword","The Brutalizer"}, {"Long Sword","The Brutalizer"}},
	"Randuin's Omen"                    -> {{"Giant's Belt","Randuin's Omen"}, {"Warden's Mail","Randuin's Omen"}, {"Cloth Armor","Warden's Mail"}, {"Cloth Armor","Warden's Mail"}},
	"Bilgewater Cutlass"                -> {{"Long Sword","Bilgewater Cutlass"}, {"Vampiric Scepter","Bilgewater Cutlass"}, {"Long Sword","Vampiric Scepter"}},
	"Overlord's Bloodmail"              -> {{"Giant's Belt","Overlord's Bloodmail"}, {"Ruby Crystal","Overlord's Bloodmail"}},
	"Hextech Gunblade"                  -> {{"Bilgewater Cutlass","Hextech Gunblade"}, {"Long Sword","Bilgewater Cutlass"}, {"Vampiric Scepter","Bilgewater Cutlass"}, {"Long Sword","Vampiric Scepter"}, {"Hextech Revolver","Hextech Gunblade"}, {"Amplifying Tome","Hextech Revolver"}, {"Amplifying Tome","Hextech Revolver"}},
	"Runaan's Hurricane (Ranged Only)"  -> {{"Dagger","Runaan's Hurricane (Ranged Only)"}, {"Recurve Bow","Runaan's Hurricane (Ranged Only)"}, {"Dagger","Runaan's Hurricane (Ranged Only)"}},
	"Will of the Ancients"              -> {{"Kage's Lucky Pick","Will of the Ancients"}, {"Amplifying Tome","Kage's Lucky Pick"}, {"Hextech Revolver","Will of the Ancients"}, {"Amplifying Tome","Hextech Revolver"}, {"Amplifying Tome","Hextech Revolver"}},
	"Blade of the Ruined King"          -> {{"Dagger","Blade of the Ruined King"}, {"Bilgewater Cutlass","Blade of the Ruined King"}, {"Long Sword","Bilgewater Cutlass"}, {"Vampiric Scepter","Bilgewater Cutlass"}, {"Long Sword","Vampiric Scepter"}, {"Dagger","Blade of the Ruined King"}},
	"Wriggle's Lantern"                 -> {{"Madred's Razors","Wriggle's Lantern"}, {"Cloth Armor","Madred's Razors"}, {"Hunter's Machete","Madred's Razors"}, {"Vampiric Scepter","Wriggle's Lantern"}, {"Long Sword","Vampiric Scepter"}},
	"Hexdrinker"                        -> {{"Long Sword","Hexdrinker"}, {"Null-Magic Mantle","Hexdrinker"}},
	"Maw of Malmortius"                 -> {{"Hexdrinker","Maw of Malmortius"}, {"Long Sword","Hexdrinker"}, {"Null-Magic Mantle","Hexdrinker"}, {"Pickaxe","Maw of Malmortius"}},
	"Zeal"                              -> {{"Brawler's Gloves","Zeal"}, {"Dagger","Zeal"}},
	"Ionian Boots of Lucidity"          -> {{"Boots of Speed","Ionian Boots of Lucidity"}},
	"Grez's Spectral Lantern"           -> {{"Cloth Armor","Grez's Spectral Lantern"}, {"Vampiric Scepter","Grez's Spectral Lantern"}, {"Long Sword","Vampiric Scepter"}},
	"Statikk Shiv"                      -> {{"Zeal","Statikk Shiv"}, {"Brawler's Gloves","Zeal"}, {"Dagger","Zeal"}, {"Avarice Blade","Statikk Shiv"}, {"Brawler's Gloves","Avarice Blade"}},
	"Morellonomicon"                    -> {{"Kage's Lucky Pick","Morellonomicon"}, {"Amplifying Tome","Kage's Lucky Pick"}, {"Faerie Charm","Morellonomicon"}, {"Fiendish Codex","Morellonomicon"}, {"Amplifying Tome","Fiendish Codex"}},
	"Moonflair Spellblade (Ranged Only)" -> {{"Seeker's Armguard","Moonflair Spellblade (Ranged Only)"}, {"Cloth Armor","Seeker's Armguard"}, {"Amplifying Tome","Seeker's Armguard"}, {"Cloth Armor","Seeker's Armguard"}, {"Negatron Cloak","Moonflair Spellblade (Ranged Only)"}},
	"Zephyr"                            -> {{"Stinger","Zephyr"}, {"Dagger","Stinger"}, {"Dagger","Stinger"}, {"Pickaxe","Zephyr"}},
	"Eleisa's Miracle"                  -> {{"Philosopher's Stone","Eleisa's Miracle"}, {"Faerie Charm","Philosopher's Stone"}, {"Rejuvenation Bead","Philosopher's Stone"}},
	"The Bloodthirster"                 -> {{"B. F. Sword","The Bloodthirster"}, {"Vampiric Scepter","The Bloodthirster"}, {"Long Sword","Vampiric Scepter"}},
	"Arcane Helix"                      -> {{"Catalyst the Protector","Arcane Helix"}, {"Ruby Crystal","Catalyst the Protector"}, {"Sapphire Crystal","Catalyst the Protector"}, {"Ruby Crystal","Arcane Helix"}},
	"Ionic Spark"                       -> {{"Recurve Bow","Ionic Spark"}, {"Ruby Crystal","Ionic Spark"}},
	"Odyn's Veil"                       -> {{"Negatron Cloak","Odyn's Veil"}, {"Catalyst the Protector","Odyn's Veil"}, {"Ruby Crystal","Catalyst the Protector"}, {"Sapphire Crystal","Catalyst the Protector"}},
	"Wooglet's Witchcap"                -> {{"Seeker's Armguard","Wooglet's Witchcap"}, {"Cloth Armor","Seeker's Armguard"}, {"Amplifying Tome","Seeker's Armguard"}, {"Cloth Armor","Seeker's Armguard"}, {"Blasting Wand","Wooglet's Witchcap"}, {"Amplifying Tome","Wooglet's Witchcap"}},
	"Priscilla's Blessing"              -> {{"Rejuvenation Bead","Priscilla's Blessing"}, {"Rejuvenation Bead","Priscilla's Blessing"}},
	"Entropy"                           -> {{"Phage","Entropy"}, {"Ruby Crystal","Phage"}, {"Long Sword","Phage"}, {"B. F. Sword","Entropy"}},
	"The Lightbringer"                  -> {{"Grez's Spectral Lantern","The Lightbringer"}, {"Cloth Armor","Grez's Spectral Lantern"}, {"Vampiric Scepter","Grez's Spectral Lantern"}, {"Long Sword","Vampiric Scepter"}, {"Pickaxe","The Lightbringer"}},
	"Kitae's Bloodrazor"                -> {{"Pickaxe","Kitae's Bloodrazor"}, {"Recurve Bow","Kitae's Bloodrazor"}},
	"Wit's End"                         -> {{"Recurve Bow","Wit's End"}, {"Null-Magic Mantle","Wit's End"}, {"Dagger","Wit's End"}},
	"Blackfire Torch"                   -> {{"Blasting Wand","Blackfire Torch"}, {"Fiendish Codex","Blackfire Torch"}, {"Amplifying Tome","Fiendish Codex"}},
	"Locket of the Iron Solari"         -> {{"Aegis of the Legion","Locket of the Iron Solari"}, {"Emblem of Valor","Aegis of the Legion"}, {"Cloth Armor","Emblem of Valor"}, {"Rejuvenation Bead","Emblem of Valor"}, {"Ruby Crystal","Aegis of the Legion"}, {"Null-Magic Mantle","Aegis of the Legion"}},
	"Seeker's Armguard"                 -> {{"Cloth Armor","Seeker's Armguard"}, {"Amplifying Tome","Seeker's Armguard"}, {"Cloth Armor","Seeker's Armguard"}},
	"Augment: Power"                    -> {{"The Hex Core","Augment: Power"}},
	"Augment: Gravity"                  -> {{"The Hex Core","Augment: Gravity"}},
	"Augment: Death"                    -> {{"The Hex Core","Augment: Death"}},
	"Enchantment: Alacrity"             -> {{"Ninja Tabi","Enchantment: Alacrity"}, {"Boots of Speed","Ninja Tabi"}, {"Cloth Armor","Ninja Tabi"}},
	"Tear of the Goddess (Crystal Scar)" -> {{"Sapphire Crystal","Tear of the Goddess (Crystal Scar)"}, {"Faerie Charm","Tear of the Goddess (Crystal Scar)"}},
	"Spirit of the Spectral Wraith"     -> {{"Spirit Stone","Spirit of the Spectral Wraith"}, {"Hunter's Machete","Spirit Stone"}, {"Faerie Charm","Spirit Stone"}, {"Rejuvenation Bead","Spirit Stone"}, {"Hextech Revolver","Spirit of the Spectral Wraith"}, {"Amplifying Tome","Hextech Revolver"}, {"Amplifying Tome","Hextech Revolver"}},
	"Spirit of the Ancient Golem"       -> {{"Spirit Stone","Spirit of the Ancient Golem"}, {"Hunter's Machete","Spirit Stone"}, {"Faerie Charm","Spirit Stone"}, {"Rejuvenation Bead","Spirit Stone"}, {"Kindlegem","Spirit of the Ancient Golem"}, {"Ruby Crystal","Kindlegem"}},
	"Spirit of the Elder Lizard"        -> {{"Spirit Stone","Spirit of the Elder Lizard"}, {"Hunter's Machete","Spirit Stone"}, {"Faerie Charm","Spirit Stone"}, {"Rejuvenation Bead","Spirit Stone"}, {"Long Sword","Spirit of the Elder Lizard"}, {"Long Sword","Spirit of the Elder Lizard"}},
	"Spectre's Cowl"                    -> {{"Ruby Crystal","Spectre's Cowl"}, {"Negatron Cloak","Spectre's Cowl"}},
	"Sanguine Blade"                    -> {{"B. F. Sword","Sanguine Blade"}, {"Vampiric Scepter","Sanguine Blade"}, {"Long Sword","Vampiric Scepter"}},
	"Mikael's Crucible"                 -> {{"Philosopher's Stone","Mikael's Crucible"}, {"Faerie Charm","Philosopher's Stone"}, {"Rejuvenation Bead","Philosopher's Stone"}, {"Chalice of Harmony","Mikael's Crucible"}, {"Faerie Charm","Chalice of Harmony"}, {"Null-Magic Mantle","Chalice of Harmony"}, {"Faerie Charm","Chalice of Harmony"}},
	"Emblem of Valor"                   -> {{"Cloth Armor","Emblem of Valor"}, {"Rejuvenation Bead","Emblem of Valor"}},
	"Guardian's Horn"                   -> {{"Rejuvenation Bead","Guardian's Horn"}, {"Ruby Crystal","Guardian's Horn"}},
	"Ravenous Hydra (Melee Only)"       -> {{"Tiamat (Melee Only)","Ravenous Hydra (Melee Only)"}, {"Pickaxe","Tiamat (Melee Only)"}, {"Long Sword","Tiamat (Melee Only)"}, {"Rejuvenation Bead","Tiamat (Melee Only)"}, {"Rejuvenation Bead","Tiamat (Melee Only)"}, {"Vampiric Scepter","Ravenous Hydra (Melee Only)"}, {"Long Sword","Vampiric Scepter"}},
	"Soul Shroud"                       -> {{"Kindlegem","Soul Shroud"}, {"Ruby Crystal","Kindlegem"}, {"Ruby Crystal","Soul Shroud"}, {"Mana Manipulator","Soul Shroud"}, {"Faerie Charm","Mana Manipulator"}},
	"Lich Bane"                         -> {{"Sheen","Lich Bane"}, {"Sapphire Crystal","Sheen"}, {"Amplifying Tome","Sheen"}, {"Blasting Wand","Lich Bane"}},
	"Enchantment: Captain"              -> {{"Boots of Mobility","Enchantment: Captain"}, {"Boots of Speed","Boots of Mobility"}},
	"Stinger"                           -> {{"Dagger","Stinger"}, {"Dagger","Stinger"}},
	"Enchantment: Homeguard"            -> {{"Berserker's Greaves","Enchantment: Homeguard"}, {"Boots of Speed","Berserker's Greaves"}, {"Dagger","Berserker's Greaves"}},
	"Hextech Sweeper"                   -> {{"Amplifying Tome","Hextech Sweeper"}, {"Amplifying Tome","Hextech Sweeper"}, {"Kindlegem","Hextech Sweeper"}, {"Ruby Crystal","Kindlegem"}},
	"Enchantment: Furor"                -> {{"Berserker's Greaves","Enchantment: Furor"}, {"Boots of Speed","Berserker's Greaves"}, {"Dagger","Berserker's Greaves"}},
	"Banshee's Veil"                    -> {{"Spectre's Cowl","Banshee's Veil"}, {"Ruby Crystal","Spectre's Cowl"}, {"Negatron Cloak","Spectre's Cowl"}, {"Ruby Crystal","Banshee's Veil"}},
	"Enchantment: Alacrity"             -> {{"Berserker's Greaves","Enchantment: Alacrity"}, {"Boots of Speed","Berserker's Greaves"}, {"Dagger","Berserker's Greaves"}},
	"Enchantment: Homeguard"            -> {{"Sorcerer's Shoes","Enchantment: Homeguard"}, {"Boots of Speed","Sorcerer's Shoes"}},
	"Enchantment: Captain"              -> {{"Sorcerer's Shoes","Enchantment: Captain"}, {"Boots of Speed","Sorcerer's Shoes"}},
	"Enchantment: Furor"                -> {{"Sorcerer's Shoes","Enchantment: Furor"}, {"Boots of Speed","Sorcerer's Shoes"}},
	"Enchantment: Distortion"           -> {{"Sorcerer's Shoes","Enchantment: Distortion"}, {"Boots of Speed","Sorcerer's Shoes"}},
	"Enchantment: Alacrity"             -> {{"Sorcerer's Shoes","Enchantment: Alacrity"}, {"Boots of Speed","Sorcerer's Shoes"}},
	"Enchantment: Homeguard"            -> {{"Ninja Tabi","Enchantment: Homeguard"}, {"Boots of Speed","Ninja Tabi"}, {"Cloth Armor","Ninja Tabi"}},
	"Enchantment: Captain"              -> {{"Ninja Tabi","Enchantment: Captain"}, {"Boots of Speed","Ninja Tabi"}, {"Cloth Armor","Ninja Tabi"}},
	"Enchantment: Furor"                -> {{"Ninja Tabi","Enchantment: Furor"}, {"Boots of Speed","Ninja Tabi"}, {"Cloth Armor","Ninja Tabi"}},
	"Enchantment: Distortion"           -> {{"Ninja Tabi","Enchantment: Distortion"}, {"Boots of Speed","Ninja Tabi"}, {"Cloth Armor","Ninja Tabi"}},
	"Thornmail"                         -> {{"Cloth Armor","Thornmail"}, {"Chain Vest","Thornmail"}},
	"Lord Van Damm's Pillager"          -> {{"Heart of Gold","Lord Van Damm's Pillager"}, {"Ruby Crystal","Heart of Gold"}, {"The Brutalizer","Lord Van Damm's Pillager"}, {"Long Sword","The Brutalizer"}, {"Long Sword","The Brutalizer"}},
	"Enchantment: Captain"              -> {{"Mercury's Treads","Enchantment: Captain"}, {"Boots of Speed","Mercury's Treads"}, {"Null-Magic Mantle","Mercury's Treads"}},
	"Enchantment: Furor"                -> {{"Mercury's Treads","Enchantment: Furor"}, {"Boots of Speed","Mercury's Treads"}, {"Null-Magic Mantle","Mercury's Treads"}},
	"Enchantment: Distortion"           -> {{"Mercury's Treads","Enchantment: Distortion"}, {"Boots of Speed","Mercury's Treads"}, {"Null-Magic Mantle","Mercury's Treads"}},
	"Enchantment: Alacrity"             -> {{"Mercury's Treads","Enchantment: Alacrity"}, {"Boots of Speed","Mercury's Treads"}, {"Null-Magic Mantle","Mercury's Treads"}},
	"Enchantment: Homeguard"            -> {{"Boots of Mobility","Enchantment: Homeguard"}, {"Boots of Speed","Boots of Mobility"}},
	"Aegis of the Legion"               -> {{"Emblem of Valor","Aegis of the Legion"}, {"Cloth Armor","Emblem of Valor"}, {"Rejuvenation Bead","Emblem of Valor"}, {"Ruby Crystal","Aegis of the Legion"}, {"Null-Magic Mantle","Aegis of the Legion"}},
	"Enchantment: Furor"                -> {{"Boots of Mobility","Enchantment: Furor"}, {"Boots of Speed","Boots of Mobility"}},
	"Enchantment: Distortion"           -> {{"Boots of Mobility","Enchantment: Distortion"}, {"Boots of Speed","Boots of Mobility"}},
	"Enchantment: Alacrity"             -> {{"Boots of Mobility","Enchantment: Alacrity"}, {"Boots of Speed","Boots of Mobility"}},
	"Enchantment: Homeguard"            -> {{"Ionian Boots of Lucidity","Enchantment: Homeguard"}, {"Boots of Speed","Ionian Boots of Lucidity"}},
	"Enchantment: Captain"              -> {{"Ionian Boots of Lucidity","Enchantment: Captain"}, {"Boots of Speed","Ionian Boots of Lucidity"}},
	"Madred's Razors"                   -> {{"Cloth Armor","Madred's Razors"}, {"Hunter's Machete","Madred's Razors"}},
	"Enchantment: Distortion"           -> {{"Ionian Boots of Lucidity","Enchantment: Distortion"}, {"Boots of Speed","Ionian Boots of Lucidity"}},
	"Enchantment: Furor"                -> {{"Ionian Boots of Lucidity","Enchantment: Furor"}, {"Boots of Speed","Ionian Boots of Lucidity"}},
	"Enchantment: Homeguard"            -> {{"Boots of Swiftness","Enchantment: Homeguard"}, {"Boots of Speed","Boots of Swiftness"}},
	"Enchantment: Captain"              -> {{"Boots of Swiftness","Enchantment: Captain"}, {"Boots of Speed","Boots of Swiftness"}},
	"Enchantment: Furor"                -> {{"Boots of Swiftness","Enchantment: Furor"}, {"Boots of Speed","Boots of Swiftness"}},
	"Enchantment: Distortion"           -> {{"Boots of Swiftness","Enchantment: Distortion"}, {"Boots of Speed","Boots of Swiftness"}},
	"Enchantment: Alacrity"             -> {{"Boots of Swiftness","Enchantment: Alacrity"}, {"Boots of Speed","Boots of Swiftness"}},
	"Enchantment: Alacrity"             -> {{"Ionian Boots of Lucidity","Enchantment: Alacrity"}, {"Boots of Speed","Ionian Boots of Lucidity"}},
	"Frozen Heart"                      -> {{"Warden's Mail","Frozen Heart"}, {"Cloth Armor","Warden's Mail"}, {"Cloth Armor","Warden's Mail"}, {"Glacial Shroud","Frozen Heart"}, {"Sapphire Crystal","Glacial Shroud"}, {"Chain Vest","Glacial Shroud"}},
	"Mercury's Treads"                  -> {{"Boots of Speed","Mercury's Treads"}, {"Null-Magic Mantle","Mercury's Treads"}},
	"Tiamat (Melee Only)"               -> {{"Pickaxe","Tiamat (Melee Only)"}, {"Long Sword","Tiamat (Melee Only)"}, {"Rejuvenation Bead","Tiamat (Melee Only)"}, {"Rejuvenation Bead","Tiamat (Melee Only)"}},
	"Rod of Ages (Crystal Scar)"        -> {{"Catalyst the Protector","Rod of Ages (Crystal Scar)"}, {"Ruby Crystal","Catalyst the Protector"}, {"Sapphire Crystal","Catalyst the Protector"}, {"Blasting Wand","Rod of Ages (Crystal Scar)"}},
	"Enchantment: Homeguard"            -> {{"Mercury's Treads","Enchantment: Homeguard"}, {"Boots of Speed","Mercury's Treads"}, {"Null-Magic Mantle","Mercury's Treads"}},
	"Infinity Edge"                     -> {{"B. F. Sword","Infinity Edge"}, {"Pickaxe","Infinity Edge"}, {"Cloak of Agility","Infinity Edge"}},
	"Kindlegem"                         -> {{"Ruby Crystal","Kindlegem"}},
	"Last Whisper"                      -> {{"Pickaxe","Last Whisper"}, {"Long Sword","Last Whisper"}},
	"Deathfire Grasp"                   -> {{"Needlessly Large Rod","Deathfire Grasp"}, {"Fiendish Codex","Deathfire Grasp"}, {"Amplifying Tome","Fiendish Codex"}},
	"Enchantment: Captain"              -> {{"Berserker's Greaves","Enchantment: Captain"}, {"Boots of Speed","Berserker's Greaves"}, {"Dagger","Berserker's Greaves"}},
	"The Black Cleaver"                 -> {{"The Brutalizer","The Black Cleaver"}, {"Long Sword","The Brutalizer"}, {"Long Sword","The Brutalizer"}, {"Ruby Crystal","The Black Cleaver"}},
	"Enchantment: Distortion"           -> {{"Berserker's Greaves","Enchantment: Distortion"}, {"Boots of Speed","Berserker's Greaves"}, {"Dagger","Berserker's Greaves"}},
	"Sunfire Cape"                      -> {{"Chain Vest","Sunfire Cape"}, {"Giant's Belt","Sunfire Cape"}},
	"Hextech Revolver"                  -> {{"Amplifying Tome","Hextech Revolver"}, {"Amplifying Tome","Hextech Revolver"}},
	"Abyssal Scepter"                   -> {{"Blasting Wand","Abyssal Scepter"}, {"Negatron Cloak","Abyssal Scepter"}},
	"Archangel's Staff"                 -> {{"Tear of the Goddess","Archangel's Staff"}, {"Sapphire Crystal","Tear of the Goddess"}, {"Faerie Charm","Tear of the Goddess"}, {"Blasting Wand","Archangel's Staff"}},
	"Manamune"                          -> {{"Tear of the Goddess","Manamune"}, {"Sapphire Crystal","Tear of the Goddess"}, {"Faerie Charm","Tear of the Goddess"}, {"Long Sword","Manamune"}},
	"Atma's Impaler"                    -> {{"Chain Vest","Atma's Impaler"}, {"Avarice Blade","Atma's Impaler"}, {"Brawler's Gloves","Avarice Blade"}},
	"Berserker's Greaves"               -> {{"Boots of Speed","Berserker's Greaves"}, {"Dagger","Berserker's Greaves"}},
	"Archangel's Staff (Crystal Scar)"  -> {{"Tear of the Goddess (Crystal Scar)","Archangel's Staff (Crystal Scar)"}, {"Sapphire Crystal","Tear of the Goddess (Crystal Scar)"}, {"Faerie Charm","Tear of the Goddess (Crystal Scar)"}, {"Blasting Wand","Archangel's Staff (Crystal Scar)"}},
	"Manamune (Crystal Scar)"           -> {{"Tear of the Goddess (Crystal Scar)","Manamune (Crystal Scar)"}, {"Sapphire Crystal","Tear of the Goddess (Crystal Scar)"}, {"Faerie Charm","Tear of the Goddess (Crystal Scar)"}, {"Long Sword","Manamune (Crystal Scar)"}},
	"Boots of Swiftness"                -> {{"Boots of Speed","Boots of Swiftness"}},
	"Catalyst the Protector"            -> {{"Ruby Crystal","Catalyst the Protector"}, {"Sapphire Crystal","Catalyst the Protector"}},
	"Sorcerer's Shoes"                  -> {{"Boots of Speed","Sorcerer's Shoes"}},
	"Frozen Mallet"                     -> {{"Phage","Frozen Mallet"}, {"Ruby Crystal","Phage"}, {"Long Sword","Phage"}, {"Giant's Belt","Frozen Mallet"}},
	"Twin Shadows"                      -> {{"Kage's Lucky Pick","Twin Shadows"}, {"Amplifying Tome","Kage's Lucky Pick"}, {"Null-Magic Mantle","Twin Shadows"}},
	"Glacial Shroud"                    -> {{"Sapphire Crystal","Glacial Shroud"}, {"Chain Vest","Glacial Shroud"}},
	"Iceborn Gauntlet"                  -> {{"Sheen","Iceborn Gauntlet"}, {"Sapphire Crystal","Sheen"}, {"Amplifying Tome","Sheen"}, {"Glacial Shroud","Iceborn Gauntlet"}, {"Sapphire Crystal","Glacial Shroud"}, {"Chain Vest","Glacial Shroud"}},
	"Guardian Angel"                    -> {{"Negatron Cloak","Guardian Angel"}, {"Chain Vest","Guardian Angel"}},
	"Rod of Ages"                       -> {{"Catalyst the Protector","Rod of Ages"}, {"Ruby Crystal","Catalyst the Protector"}, {"Sapphire Crystal","Catalyst the Protector"}, {"Blasting Wand","Rod of Ages"}},
	"Chalice of Harmony"                -> {{"Faerie Charm","Chalice of Harmony"}, {"Null-Magic Mantle","Chalice of Harmony"}, {"Faerie Charm","Chalice of Harmony"}},
	"Athene's Unholy Grail"             -> {{"Fiendish Codex","Athene's Unholy Grail"}, {"Amplifying Tome","Fiendish Codex"}, {"Chalice of Harmony","Athene's Unholy Grail"}, {"Faerie Charm","Chalice of Harmony"}, {"Null-Magic Mantle","Chalice of Harmony"}, {"Faerie Charm","Chalice of Harmony"}},
	"Spirit Visage"                     -> {{"Spectre's Cowl","Spirit Visage"}, {"Ruby Crystal","Spectre's Cowl"}, {"Negatron Cloak","Spectre's Cowl"}, {"Kindlegem","Spirit Visage"}, {"Ruby Crystal","Kindlegem"}},
	"Liandry's Torment"                 -> {{"Haunting Guise","Liandry's Torment"}, {"Ruby Crystal","Haunting Guise"}, {"Amplifying Tome","Haunting Guise"}, {"Amplifying Tome","Liandry's Torment"}},
	"Mana Manipulator"                  -> {{"Faerie Charm","Mana Manipulator"}},
	"Mejai's Soulstealer"               -> {{"Amplifying Tome","Mejai's Soulstealer"}},
	"Phage"                             -> {{"Ruby Crystal","Phage"}, {"Long Sword","Phage"}},
	"Phantom Dancer"                    -> {{"Cloak of Agility","Phantom Dancer"}, {"Zeal","Phantom Dancer"}, {"Brawler's Gloves","Zeal"}, {"Dagger","Zeal"}, {"Dagger","Phantom Dancer"}},
	"Ninja Tabi"                        -> {{"Boots of Speed","Ninja Tabi"}, {"Cloth Armor","Ninja Tabi"}},
	"Zeke's Herald"                     -> {{"Kindlegem","Zeke's Herald"}, {"Ruby Crystal","Kindlegem"}, {"Vampiric Scepter","Zeke's Herald"}, {"Long Sword","Vampiric Scepter"}},
	"Ohmwrecker"                        -> {{"Ruby Crystal","Ohmwrecker"}, {"Philosopher's Stone","Ohmwrecker"}, {"Faerie Charm","Philosopher's Stone"}, {"Rejuvenation Bead","Philosopher's Stone"}, {"Blasting Wand","Ohmwrecker"}},
	"Sheen"                             -> {{"Sapphire Crystal","Sheen"}, {"Amplifying Tome","Sheen"}},
	"Banner of Command"                 -> {{"Fiendish Codex","Banner of Command"}, {"Amplifying Tome","Fiendish Codex"}, {"Emblem of Valor","Banner of Command"}, {"Cloth Armor","Emblem of Valor"}, {"Rejuvenation Bead","Emblem of Valor"}},
	"Ruby Sightstone"                   -> {{"Sightstone","Ruby Sightstone"}, {"Ruby Crystal","Sightstone"}, {"Ruby Crystal","Ruby Sightstone"}},
	"Tear of the Goddess"               -> {{"Sapphire Crystal","Tear of the Goddess"}, {"Faerie Charm","Tear of the Goddess"}},
	"Zhonya's Hourglass"                -> {{"Seeker's Armguard","Zhonya's Hourglass"}, {"Cloth Armor","Seeker's Armguard"}, {"Amplifying Tome","Seeker's Armguard"}, {"Cloth Armor","Seeker's Armguard"}, {"Needlessly Large Rod","Zhonya's Hourglass"}}
};
