#include "db_layout.h"
const char *db_names[DB_LEN] = {
"(NULL-ITEM)",
"Boots of Speed",
"Faerie Charm",
"Meki Pendant",
"Rejuvenation Bead",
"Regrowth Pendant",
"Giant's Belt",
"Cloak of Agility",
"Blasting Wand",
"Sapphire Crystal",
"Ruby Crystal",
"Cloth Armor",
"Chain Vest",
"Null-Magic Mantle",
"Long Sword",
"Pickaxe",
"B. F. Sword",
"Hunter's Machete",
"Dagger",
"Recurve Bow",
"Brawler's Gloves",
"Amplifying Tome",
"Vampiric Scepter",
"Doran's Shield",
"Doran's Blade",
"Doran's Ring",
"Negatron Cloak",
"Needlessly Large Rod",
"Prospector's Blade",
"Prospector's Ring",
"Spirit Stone",
"Health Potion",
"Mana Potion",
"Total Biscuit of Rejuvenation",
"Elixir of Fortitude",
"Elixir of Agility",
"Elixir of Brilliance",
"Ichor of Rage",
"Crystalline Flask",
"Oracle's Elixir",
"Vision Ward",
"Sight Ward",
"Ruby Sightstone",
"Oracle's Extract",
"Ichor of Illumination",
"Sightstone",
"Explorer's Ward",
"Guardian's Horn",
"Poro-Snax",
"Abyssal Scepter",
"Archangel's Staff",
"Manamune",
"Atma's Impaler",
"Berserker's Greaves",
"Archangel's Staff (Crystal Scar)",
"Manamune (Crystal Scar)",
"Boots of Swiftness",
"Catalyst the Protector",
"Sorcerer's Shoes",
"Frozen Mallet",
"Twin Shadows",
"Glacial Shroud",
"Iceborn Gauntlet",
"Guardian Angel",
"Rod of Ages",
"Chalice of Harmony",
"Rod of Ages (Crystal Scar)",
"Infinity Edge",
"Last Whisper",
"Mana Manipulator",
"Seraph's Embrace",
"Mejai's Soulstealer",
"Muramana",
"Phage",
"Phantom Dancer",
"Ninja Tabi",
"Zeke's Herald",
"Ohmwrecker",
"Sheen",
"Banner of Command",
"Spirit Visage",
"Kindlegem",
"Sunfire Cape",
"Shurelya's Reverie",
"Tear of the Goddess",
"The Black Cleaver",
"The Bloodthirster",
"Tear of the Goddess (Crystal Scar)",
"Ravenous Hydra (Melee Only)",
"Thornmail",
"Tiamat (Melee Only)",
"Trinity Force",
"Warden's Mail",
"Warmog's Armor",
"Overlord's Bloodmail",
"Runaan's Hurricane (Ranged Only)",
"Zeal",
"Statikk Shiv",
"Rabadon's Deathcap",
"Wooglet's Witchcap",
"Wit's End",
"Shard of True Ice",
"Avarice Blade",
"Philosopher's Stone",
"Emblem of Valor",
"Kage's Lucky Pick",
"Soul Shroud",
"Lich Bane",
"Stinger",
"Banshee's Veil",
"Lord Van Damm's Pillager",
"Aegis of the Legion",
"Madred's Razors",
"Runic Bulwark",
"Fiendish Codex",
"Force of Nature",
"Frozen Heart",
"Mercury's Treads",
"Orb of Winter",
"Malady",
"Nashor's Tooth",
"Rylai's Crystal Scepter",
"Boots of Mobility",
"Wicked Hatchet",
"Executioner's Calling",
"Guinsoo's Rageblade",
"Madred's Bloodrazor",
"Deathfire Grasp",
"Sword of the Divine",
"Heart of Gold",
"The Brutalizer",
"Void Staff",
"Haunting Guise",
"Leviathan",
"Mercurial Scimitar",
"Quicksilver Sash",
"Sword of the Occult",
"Youmuu's Ghostblade",
"Randuin's Omen",
"Bilgewater Cutlass",
"Hextech Revolver",
"Hextech Gunblade",
"Liandry's Torment",
"Will of the Ancients",
"Blade of the Ruined King",
"Wriggle's Lantern",
"Hexdrinker",
"Maw of Malmortius",
"Zhonya's Hourglass",
"Ionian Boots of Lucidity",
"Grez's Spectral Lantern",
"Morellonomicon",
"Bonetooth Necklace",
"Bonetooth Necklace",
"Bonetooth Necklace",
"Bonetooth Necklace",
"Moonflair Spellblade (Ranged Only)",
"Bonetooth Necklace",
"Zephyr",
"Eleisa's Miracle",
"Athene's Unholy Grail",
"Head of Kha'Zix",
"Arcane Helix",
"Ionic Spark",
"Odyn's Veil",
"Sanguine Blade",
"Priscilla's Blessing",
"Entropy",
"The Lightbringer",
"Kitae's Bloodrazor",
"Hextech Sweeper",
"Blackfire Torch",
"Locket of the Iron Solari",
"Seeker's Armguard",
"Augment: Power",
"Augment: Gravity",
"Augment: Death",
"The Hex Core",
"Spirit of the Spectral Wraith",
"Spirit of the Ancient Golem",
"Spirit of the Elder Lizard",
"Spectre's Cowl",
"Mikael's Crucible",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity",
"Enchantment: Homeguard",
"Enchantment: Captain",
"Enchantment: Furor",
"Enchantment: Distortion",
"Enchantment: Alacrity"
};

